// errCode generated by gocode. DO NOT EDIT!
package admin

import (
	"context"
	"github.com/qiaogw/gocode/common/modelx"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"

	"gorm.io/gorm"

	_ "github.com/lib/pq"
)

type (
	deptModel interface {
		Insert(ctx context.Context, data *Dept) (*Dept, error)
		FindOne(ctx context.Context, id interface{}) (*Dept, error)
		Update(ctx context.Context, newData *Dept) error
		Delete(ctx context.Context, id interface{}) error
	}

	defaultDeptModel struct {
		sqlc.CachedConn
		table  string
		gormDB *gorm.DB
	}

	Dept struct {
		modelx.BaseModel
		ParentId int64   `json:"parentId" form:"parentId" db:"parent_id" gorm:"column:parent_id;comment:上级部门;"`
		Name     string  `json:"name" form:"name" db:"name" gorm:"column:name;comment:部门名称;"`
		Sort     int64   `json:"sort" form:"sort" db:"sort" gorm:"column:sort;comment:排序;"`
		Leader   string  `json:"leader" form:"leader" db:"leader" gorm:"column:leader;comment:领导;"`
		Phone    string  `json:"phone" form:"phone" db:"phone" gorm:"column:phone;comment:电话;"`
		Email    string  `json:"email" form:"email" db:"email" gorm:"column:email;comment:email;"`
		Enabled  bool    `json:"enabled" form:"enabled" db:"enabled" gorm:"column:enabled;comment:可用;"`
		Users    []*User `json:"users" db:"-"`
		modelx.ControlBy
		modelx.ModelTime
	}
)

// TableName Dept 表名
func (Dept) TableName() string {
	return "admin_dept"
}

func newDeptModel(conn sqlx.SqlConn, c cache.CacheConf, gormx *gorm.DB) *defaultDeptModel {
	return &defaultDeptModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "admin_dept",
		gormDB:     gormx,
	}
}

func (m *defaultDeptModel) FindOne(ctx context.Context, id interface{}) (*Dept, error) {
	var resp Dept
	err := m.gormDB.First(&resp, id).Error
	switch err {
	case nil:
		return &resp, nil
	default:
		if err.Error() == modelx.ErrNotFound.Error() {
			return nil, modelx.ErrNotFound
		}
		return nil, err
	}
}

func (m *defaultDeptModel) Insert(ctx context.Context, data *Dept) (*Dept, error) {
	err := m.gormDB.Create(data).Error
	//var re sql.Result

	return data, err
}

func (m *defaultDeptModel) Update(ctx context.Context, newData *Dept) error {
	_, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	err = m.gormDB.Save(newData).Error
	return err
}

func (m *defaultDeptModel) Delete(ctx context.Context, id interface{}) error {
	_, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	err = m.gormDB.Delete(&Dept{}, id).Error
	return err
}

func (m *defaultDeptModel) tableName() string {
	return m.table
}
