// errCode generated by gocode. DO NOT EDIT!
package admin

import (
	"context"
	"github.com/qiaogw/gocode/common/modelx"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"gorm.io/gorm"

	_ "github.com/lib/pq"
)

type (
	dictTypeModel interface {
		Insert(ctx context.Context, data *DictType) (*DictType, error)
		FindOne(ctx context.Context, id interface{}) (*DictType, error)
		Update(ctx context.Context, newData *DictType) error
		Delete(ctx context.Context, id interface{}) error
	}

	defaultDictTypeModel struct {
		sqlc.CachedConn
		table  string
		gormDB *gorm.DB
	}

	DictType struct {
		modelx.BaseModel
		Name      string      `json:"name" form:"name" db:"name" gorm:"column:name;comment:字典名称;"`
		Type      string      `json:"type" form:"type" db:"type" gorm:"column:type;comment:字典代码;"`
		Enabled   bool        `json:"enabled" form:"enabled" db:"enabled" gorm:"column:enabled;comment:可用;"`
		Remark    string      `json:"remark" form:"remark" db:"remark" gorm:"column:remark;comment:备注;"`
		DictDatas []*DictData `json:"dictDatas" db:"-" `
		modelx.ControlBy
		modelx.ModelTime
	}
)

// TableName DictType 表名
func (DictType) TableName() string {
	return "admin_dict_type"
}

func newDictTypeModel(conn sqlx.SqlConn, c cache.CacheConf, gormx *gorm.DB) *defaultDictTypeModel {
	return &defaultDictTypeModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "admin_dict_type",
		gormDB:     gormx,
	}
}

func (m *defaultDictTypeModel) FindOne(ctx context.Context, id interface{}) (*DictType, error) {
	var resp DictType
	err := m.gormDB.First(&resp, id).Error
	switch err {
	case nil:
		return &resp, nil
	default:
		if err.Error() == modelx.ErrNotFound.Error() {
			return nil, modelx.ErrNotFound
		}
		return nil, err
	}
}

func (m *defaultDictTypeModel) Insert(ctx context.Context, data *DictType) (*DictType, error) {
	err := m.gormDB.Create(data).Error
	//var re sql.Result

	return data, err
}

func (m *defaultDictTypeModel) Update(ctx context.Context, newData *DictType) error {
	_, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	err = m.gormDB.Save(newData).Error
	return err
}

func (m *defaultDictTypeModel) Delete(ctx context.Context, id interface{}) error {
	_, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	err = m.gormDB.Delete(&DictType{}, id).Error
	return err
}

func (m *defaultDictTypeModel) tableName() string {
	return m.table
}
