// errCode generated by gocode. DO NOT EDIT!
package admin

import (
	"context"
	"github.com/qiaogw/gocode/common/modelx"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"

	"gorm.io/gorm"

	_ "github.com/lib/pq"
)

type (
	postModel interface {
		Insert(ctx context.Context, data *Post) (*Post, error)
		FindOne(ctx context.Context, id interface{}) (*Post, error)
		Update(ctx context.Context, newData *Post) error
		Delete(ctx context.Context, id interface{}) error
	}

	defaultPostModel struct {
		sqlc.CachedConn
		table  string
		gormDB *gorm.DB
	}

	Post struct {
		modelx.BaseModel
		Name   string  `json:"name" form:"name" db:"name" gorm:"column:name;comment:名称;"`
		Code   string  `json:"code" form:"code" db:"code" gorm:"column:code;comment:职务代码;"`
		Sort   int64   `json:"sort" form:"sort" db:"sort" gorm:"column:sort;comment:排序;"`
		Remark string  `json:"remark" form:"remark" db:"remark" gorm:"column:remark;comment:说明;"`
		Users  []*User `json:"users" db:"-"`
		modelx.ControlBy
		modelx.ModelTime
	}
)

// TableName Post 表名
func (Post) TableName() string {
	return "admin_post"
}

func newPostModel(conn sqlx.SqlConn, c cache.CacheConf, gormx *gorm.DB) *defaultPostModel {
	return &defaultPostModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "admin_post",
		gormDB:     gormx,
	}
}

func (m *defaultPostModel) FindOne(ctx context.Context, id interface{}) (*Post, error) {
	var resp Post
	err := m.gormDB.First(&resp, id).Error
	switch err {
	case nil:
		return &resp, nil
	default:
		if err.Error() == modelx.ErrNotFound.Error() {
			return nil, modelx.ErrNotFound
		}
		return nil, err
	}
}

func (m *defaultPostModel) Insert(ctx context.Context, data *Post) (*Post, error) {
	err := m.gormDB.Create(data).Error
	//var re sql.Result

	return data, err
}

func (m *defaultPostModel) Update(ctx context.Context, newData *Post) error {
	_, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	err = m.gormDB.Save(newData).Error
	return err
}

func (m *defaultPostModel) Delete(ctx context.Context, id interface{}) error {
	_, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	err = m.gormDB.Delete(&Post{}, id).Error
	return err
}

func (m *defaultPostModel) tableName() string {
	return m.table
}
