// Code generated by gocode. DO NOT EDIT!
package model
{{$table:=.Table}}
import (
	"{{.ParentPkg}}/common/global"
	"context"
    "database/sql"
    "fmt"
    "strings"
    "github.com/zeromicro/go-zero/core/stores/builder"
    "github.com/zeromicro/go-zero/core/stores/cache"
    "github.com/zeromicro/go-zero/core/stores/sqlc"
    "github.com/zeromicro/go-zero/core/stores/sqlx"
    "github.com/zeromicro/go-zero/core/stringx"

    "gorm.io/gorm"
	{{ if .HasTimer }}"time"{{ end }}
	{{ if .PostgreSql }}_ "github.com/lib/pq"{{ end}}
)

var (
	{{.PackageName}}FieldNames          = builder.RawFieldNames(&{{.Table}}{}{{if .PostgreSql}},true{{end}})
	{{.PackageName}}Rows                = strings.Join({{.PackageName}}FieldNames, ",")
	{{.PackageName}}RowsExpectAutoSet   = strings.Join(stringx.Remove({{.PackageName}}FieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	{{.PackageName}}RowsWithPlaceHolder = strings.Join(stringx.Remove({{.PackageName}}FieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cache{{.Service}}{{.Table}}IdPrefix     = "cache:{{.Db}}:{{.PackageName}}:id:"
	{{- range  .CacheKeys}}
		{{.Key}}Prefix="{{.Value}}"
	{{- end }}
)

type (
	{{.PackageName}}Model interface {
		Insert(ctx context.Context, data *{{.Table}}) (sql.Result, error)
		FindOne(ctx context.Context, id interface{}) (*{{.Table}}, error)
		Update(ctx context.Context, newData *{{.Table}}) error
		Delete(ctx context.Context, id interface{}) error
	{{- range  .CacheKeys}}
		FindOneBy{{.Field}}(ctx context.Context, {{.FieldJson}} string) (*{{$table}}, error)
	{{- end }}
	}

	default{{.Table}}Model struct {
		sqlc.CachedConn
		table  string
		gormDB *gorm.DB
	}

	{{.Table}} struct {
		global.BaseModel
        {{- range .Columns }}
			{{- if .IsPk -}}
			{{- else}}
				{{- if .IsPage}}
				{{- else}}
				{{.FieldName}}  {{.DataType}} `json:"{{.FieldJson}}" form:"{{.FieldJson}}" db:"{{.Name}}" {{- if ne .GormName "-" }} gorm:"column:{{.GormName}};{{- if .DataTypeLong -}}size:{{.DataTypeLong}};{{- end -}}comment:{{.Comment}};"{{- end -}}`
				{{- end -}}
			{{- end -}}
        {{- end }}
		global.ControlBy
        global.ModelTime
	}
)

{{ if .Table }}
// TableName {{.Table}} 表名
func ({{.Table}}) TableName() string {
  return "{{.Name}}"
}
{{ end }}

func new{{.Table}}Model(conn sqlx.SqlConn, c cache.CacheConf, gormx *gorm.DB) *default{{.Table}}Model {
	return &default{{.Table}}Model{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "{{.Name}}",
		gormDB:     gormx,
	}
}

func (m *default{{.Table}}Model) FindOne(ctx context.Context, id interface{}) (*{{.Table}}, error) {
	{{.Db}}{{.Table}}IdKey := fmt.Sprintf("%s%v", cache{{.Service}}{{.Table}}IdPrefix, id)
	var resp {{.Table}}
	err := m.QueryRow(&resp, {{.Db}}{{.Table}}IdKey, func(conn sqlx.SqlConn, v interface{}) error {
	query, values := m.GeneralSQL(func(tx *gorm.DB) *gorm.DB {
	return tx.First(&resp, id)
	})
	return conn.QueryRow(v, query, values...)
	})
	switch err {
	case nil:
	return &resp, nil
	case sqlc.ErrNotFound:
	return nil, global.ErrNotFound
	default:
	return nil, err
	}
}

{{- range  .CacheKeys}}
func (m *default{{$table}}Model) FindOneBy{{.Field}}(ctx context.Context, {{.FieldJson}} string) (*{{$table}}, error) {
	{{.Key}}Key := fmt.Sprintf("%s%v", {{.Key}}Prefix, {{.FieldJson}})
	var resp {{$table}}
	err := m.QueryRow(&resp, {{.Key}}Key, func(conn sqlx.SqlConn, v interface{}) error {
		query, values := m.GeneralSQL(func(tx *gorm.DB) *gorm.DB {
			return tx.Where("{{.FieldJson}} = ?",{{.FieldJson}}).First(&resp)
		})
		return conn.QueryRow(v, query, values...)
	})
	switch err {
	case nil:
	return &resp, nil
	case sqlc.ErrNotFound:
	return nil, global.ErrNotFound
	default:
	return nil, err
	}
}
{{- end }}


func (m *default{{.Table}}Model) Insert(ctx context.Context, data *{{.Table}}) (sql.Result, error) {
	{{.Db}}{{.Table}}IdKey := fmt.Sprintf("%s%v", cache{{.Service}}{{.Table}}IdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query, values := m.GeneralSQL(func(tx *gorm.DB) *gorm.DB {
			return tx.Create(data)
		})
		return conn.ExecCtx(ctx, query, values...)

	}, {{.Db}}{{.Table}}IdKey)
	return ret, err
}

func (m *default{{.Table}}Model) Update(ctx context.Context, newData *{{.Table}}) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	{{.Db}}{{.Table}}IdKey := fmt.Sprintf("%s%v", cache{{.Service}}{{.Table}}IdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query, values := m.GeneralSQL(func(tx *gorm.DB) *gorm.DB {
			return tx.Save(newData)
		})
		return conn.ExecCtx(ctx, query, values...)
	}, {{.Db}}{{.Table}}IdKey)
	return err
}

func (m *default{{.Table}}Model) Delete(ctx context.Context, id interface{}) error {
	_, err := m.FindOne(ctx, id)
	if err != nil {
	return err
	}

	{{.Db}}{{.Table}}IdKey := fmt.Sprintf("%s%v", cache{{.Service}}{{.Table}}IdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
	query, values := m.GeneralSQL(func(tx *gorm.DB) *gorm.DB {
	return tx.Delete(&{{.Table}}{}, id)
	})
	return conn.ExecCtx(ctx, query, values...)
	}, {{.Db}}{{.Table}}IdKey)
	return err
}

func (m *default{{.Table}}Model) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cache{{.Service}}{{.Table}}IdPrefix, primary)
}

func (m *default{{.Table}}Model) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", {{.PackageName}}Rows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *default{{.Table}}Model) tableName() string {
	return m.table
}

func (m *default{{.Table}}Model) GeneralSQL(queryFn func(tx *gorm.DB) *gorm.DB) (string, []interface{}) {
	tx := queryFn(m.gormDB.Session(&gorm.Session{DryRun: true}))
	stmt := tx.Statement
	return stmt.SQL.String(), stmt.Vars
}


